# Data Preprocessing & Feature Engineering
## Objectives

This notebook prepares the maternal health dataset for machine learning by:

- Removing unnecessary features
- Encoding categorical variables
- Creating a processed dataset
- Standardizing numerical variables
- Saving both processed and standardized datasets

In [1]:
# Import Libraries

import polars as pl
from pathlib import Path

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
# Display Settings

pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_rows(20)

polars.config.Config

In [4]:
# Load Dataset

df = pl.read_csv("../data/raw/maternal_health_dataset.csv")

df.head()

shape: (5, 18)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ id  ┆ age ┆ gra ┆ par ┆ ges ┆ bmi ┆ sys ┆ dia ┆ hem ┆ ane ┆ fas ┆ pro ┆ hiv ┆ anc ┆ del ┆ pri ┆ pre ┆ ris │
│ --- ┆ _ye ┆ vid ┆ ity ┆ tat ┆ _pr ┆ tol ┆ sto ┆ ogl ┆ mia ┆ tin ┆ tei ┆ _st ┆ _vi ┆ ive ┆ mar ┆ gna ┆ k_l │
│ i64 ┆ ars ┆ ity ┆ --- ┆ ion ┆ e_p ┆ ic_ ┆ lic ┆ obi ┆ _st ┆ g_g ┆ nur ┆ atu ┆ sit ┆ ry_ ┆ y_c ┆ ncy ┆ eve │
│     ┆ --- ┆ --- ┆ i64 ┆ al_ ┆ reg ┆ bp_ ┆ _bp ┆ n_g ┆ atu ┆ luc ┆ ia  ┆ s   ┆ s   ┆ mod ┆ omp ┆ _ou ┆ l   │
│     ┆ i64 ┆ i64 ┆     ┆ age ┆ nan ┆ mmh ┆ _mm ┆ dl  ┆ s   ┆ ose ┆ --- ┆ --- ┆ --- ┆ e   ┆ lic ┆ tco ┆ --- │
│     ┆     ┆     ┆     ┆ _we ┆ cy  ┆ g   ┆ hg  ┆ --- ┆ --- ┆ _mg ┆ i64 ┆ i64 ┆ i64 ┆ --- ┆ ati ┆ me  ┆ str │
│     ┆     ┆     ┆     ┆ eks ┆ --- ┆ --- ┆ --- ┆ f64 ┆ str ┆ dl  ┆     ┆     ┆     ┆ str ┆ on  ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ i64 ┆ i64 ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     │
│     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 1   ┆ 23  ┆ 3   ┆ 2   ┆ 33. ┆ 24. ┆ 121 ┆ 80  ┆ 10. ┆ mil ┆ 75  ┆ 0   ┆ 0   ┆ 6   ┆ vag ┆ non ┆ liv ┆ low │
│     ┆     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆     ┆ 9   ┆ d   ┆     ┆     ┆     ┆     ┆ ina ┆ e   ┆ e_b ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ irt ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     │
│ 2   ┆ 28  ┆ 5   ┆ 4   ┆ 31. ┆ 15. ┆ 103 ┆ 68  ┆ 10. ┆ mil ┆ 74  ┆ 0   ┆ 0   ┆ 4   ┆ vag ┆ non ┆ liv ┆ low │
│     ┆     ┆     ┆     ┆ 0   ┆ 4   ┆     ┆     ┆ 5   ┆ d   ┆     ┆     ┆     ┆     ┆ ina ┆ e   ┆ e_b ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ irt ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     │
│ 3   ┆ 20  ┆ 3   ┆ 1   ┆ 24. ┆ 29. ┆ 117 ┆ 65  ┆ 12. ┆ non ┆ 85  ┆ 0   ┆ 1   ┆ 5   ┆ vag ┆ non ┆ liv ┆ hig │
│     ┆     ┆     ┆     ┆ 5   ┆ 9   ┆     ┆     ┆ 5   ┆ e   ┆     ┆     ┆     ┆     ┆ ina ┆ e   ┆ e_b ┆ h   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ irt ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     │
│ 4   ┆ 31  ┆ 2   ┆ 1   ┆ 33. ┆ 23. ┆ 131 ┆ 99  ┆ 12. ┆ non ┆ 87  ┆ 2   ┆ 0   ┆ 4   ┆ vag ┆ pre ┆ liv ┆ mod │
│     ┆     ┆     ┆     ┆ 5   ┆ 0   ┆     ┆     ┆ 9   ┆ e   ┆     ┆     ┆     ┆     ┆ ina ┆ ecl ┆ e_b ┆ era │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ amp ┆ irt ┆ te  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sia ┆ h   ┆     │
│ 5   ┆ 32  ┆ 9   ┆ 8   ┆ 22. ┆ 25. ┆ 159 ┆ 90  ┆ 12. ┆ non ┆ 77  ┆ 4   ┆ 0   ┆ 4   ┆ vag ┆ pre ┆ liv ┆ mod │
│     ┆     ┆     ┆     ┆ 3   ┆ 4   ┆     ┆     ┆ 3   ┆ e   ┆     ┆     ┆     ┆     ┆ ina ┆ ecl ┆ e_b ┆ era │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ amp ┆ irt ┆ te  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sia ┆ h   ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [5]:
df = df.drop([
    "id",
    "anemia_status",
    "primary_complication"
])

df.columns

['age_years',
 'gravidity',
 'parity',
 'gestational_age_weeks',
 'bmi_pre_pregnancy',
 'systolic_bp_mmhg',
 'diastolic_bp_mmhg',
 'hemoglobin_gdl',
 'fasting_glucose_mgdl',
 'proteinuria',
 'hiv_status',
 'anc_visits',
 'delivery_mode',
 'pregnancy_outcome',
 'risk_level']

## Observation

Three non-predictive or redundant features were removed to improve model generalisation and reduce the likelihood of data leakage.

In [6]:
df.dtypes

[Int64,
 Int64,
 Int64,
 Float64,
 Float64,
 Int64,
 Int64,
 Float64,
 Int64,
 Int64,
 Int64,
 Int64,
 String,
 String,
 String]

## Observation

The dataset contains both numerical and categorical variables. Categorical variables will be encoded before model training.

In [7]:
categorical_columns = [
    "delivery_mode",
    "pregnancy_outcome",
    "risk_level"
]

encoders = {}

for col in categorical_columns:
    encoder = LabelEncoder()

    df = df.with_columns(
        pl.Series(
            col,
            encoder.fit_transform(df[col])
        )
    )

    encoders[col] = encoder

df.head()

shape: (5, 15)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ age ┆ gra ┆ par ┆ ges ┆ bmi ┆ sys ┆ dia ┆ hem ┆ fas ┆ pro ┆ hiv ┆ anc_vi ┆ deliv ┆ pregn ┆ risk_ │
│ _ye ┆ vid ┆ ity ┆ tat ┆ _pr ┆ tol ┆ sto ┆ ogl ┆ tin ┆ tei ┆ _st ┆ sits   ┆ ery_m ┆ ancy_ ┆ level │
│ ars ┆ ity ┆ --- ┆ ion ┆ e_p ┆ ic_ ┆ lic ┆ obi ┆ g_g ┆ nur ┆ atu ┆ ---    ┆ ode   ┆ outco ┆ ---   │
│ --- ┆ --- ┆ i64 ┆ al_ ┆ reg ┆ bp_ ┆ _bp ┆ n_g ┆ luc ┆ ia  ┆ s   ┆ i64    ┆ ---   ┆ me    ┆ i64   │
│ i64 ┆ i64 ┆     ┆ age ┆ nan ┆ mmh ┆ _mm ┆ dl  ┆ ose ┆ --- ┆ --- ┆        ┆ i64   ┆ ---   ┆       │
│     ┆     ┆     ┆ _we ┆ cy  ┆ g   ┆ hg  ┆ --- ┆ _mg ┆ i64 ┆ i64 ┆        ┆       ┆ i64   ┆       │
│     ┆     ┆     ┆ eks ┆ --- ┆ --- ┆ --- ┆ f64 ┆ dl  ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆ --- ┆ f64 ┆ i64 ┆ i64 ┆     ┆ --- ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ 23  ┆ 3   ┆ 2   ┆ 33. ┆ 24. ┆ 121 ┆ 80  ┆ 10. ┆ 75  ┆ 0   ┆ 0   ┆ 6      ┆ 1     ┆ 0     ┆ 1     │
│     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 28  ┆ 5   ┆ 4   ┆ 31. ┆ 15. ┆ 103 ┆ 68  ┆ 10. ┆ 74  ┆ 0   ┆ 0   ┆ 4      ┆ 1     ┆ 0     ┆ 1     │
│     ┆     ┆     ┆ 0   ┆ 4   ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 20  ┆ 3   ┆ 1   ┆ 24. ┆ 29. ┆ 117 ┆ 65  ┆ 12. ┆ 85  ┆ 0   ┆ 1   ┆ 5      ┆ 1     ┆ 0     ┆ 0     │
│     ┆     ┆     ┆ 5   ┆ 9   ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 31  ┆ 2   ┆ 1   ┆ 33. ┆ 23. ┆ 131 ┆ 99  ┆ 12. ┆ 87  ┆ 2   ┆ 0   ┆ 4      ┆ 1     ┆ 0     ┆ 2     │
│     ┆     ┆     ┆ 5   ┆ 0   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 32  ┆ 9   ┆ 8   ┆ 22. ┆ 25. ┆ 159 ┆ 90  ┆ 12. ┆ 77  ┆ 4   ┆ 0   ┆ 4      ┆ 1     ┆ 0     ┆ 2     │
│     ┆     ┆     ┆ 3   ┆ 4   ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┘

## Observation

Categorical variables were converted into numerical labels to make them suitable for machine learning algorithms.

In [8]:
processed_path = Path("../data/processed")

processed_path.mkdir(parents=True, exist_ok=True)

df.write_csv(
    processed_path / "maternal_health_processed.csv"
)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.

## Observation

The processed dataset was saved before feature scaling. This version will be used for tree-based algorithms such as Decision Tree and Random Forest.

In [9]:
numerical_columns = [
    "age_years",
    "gravidity",
    "parity",
    "gestational_age_weeks",
    "bmi_pre_pregnancy",
    "systolic_bp_mmhg",
    "diastolic_bp_mmhg",
    "hemoglobin_gdl",
    "fasting_glucose_mgdl",
    "proteinuria",
    "hiv_status",
    "anc_visits"
]

scaler = StandardScaler()

scaled_values = scaler.fit_transform(
    df.select(numerical_columns).to_numpy()
)

In [10]:
scaled_df = df.with_columns([
    pl.Series(
        col,
        scaled_values[:, i]
    )
    for i, col in enumerate(numerical_columns)
])

scaled_df.head()

shape: (5, 15)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ age ┆ gra ┆ par ┆ ges ┆ bmi ┆ sys ┆ dia ┆ hem ┆ fas ┆ pro ┆ hiv ┆ anc_vi ┆ deliv ┆ pregn ┆ risk_ │
│ _ye ┆ vid ┆ ity ┆ tat ┆ _pr ┆ tol ┆ sto ┆ ogl ┆ tin ┆ tei ┆ _st ┆ sits   ┆ ery_m ┆ ancy_ ┆ level │
│ ars ┆ ity ┆ --- ┆ ion ┆ e_p ┆ ic_ ┆ lic ┆ obi ┆ g_g ┆ nur ┆ atu ┆ ---    ┆ ode   ┆ outco ┆ ---   │
│ --- ┆ --- ┆ f64 ┆ al_ ┆ reg ┆ bp_ ┆ _bp ┆ n_g ┆ luc ┆ ia  ┆ s   ┆ f64    ┆ ---   ┆ me    ┆ i64   │
│ f64 ┆ f64 ┆     ┆ age ┆ nan ┆ mmh ┆ _mm ┆ dl  ┆ ose ┆ --- ┆ --- ┆        ┆ i64   ┆ ---   ┆       │
│     ┆     ┆     ┆ _we ┆ cy  ┆ g   ┆ hg  ┆ --- ┆ _mg ┆ f64 ┆ f64 ┆        ┆       ┆ i64   ┆       │
│     ┆     ┆     ┆ eks ┆ --- ┆ --- ┆ --- ┆ f64 ┆ dl  ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆     ┆ --- ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ -0. ┆ -0. ┆ -0. ┆ 0.8 ┆ 0.2 ┆ 0.2 ┆ 0.6 ┆ 0.2 ┆ -0. ┆ -0. ┆ -0. ┆ 0.9387 ┆ 1     ┆ 0     ┆ 1     │
│ 552 ┆ 078 ┆ 031 ┆ 775 ┆ 316 ┆ 999 ┆ 639 ┆ 807 ┆ 821 ┆ 438 ┆ 335 ┆ 08     ┆       ┆       ┆       │
│ 348 ┆ 263 ┆ 894 ┆ 62  ┆ 66  ┆ 44  ┆ 32  ┆ 73  ┆ 646 ┆ 478 ┆ 121 ┆        ┆       ┆       ┆       │
│ 0.3 ┆ 0.8 ┆ 0.8 ┆ 0.5 ┆ -1. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0463 ┆ 1     ┆ 0     ┆ 1     │
│ 532 ┆ 161 ┆ 724 ┆ 039 ┆ 936 ┆ 830 ┆ 424 ┆ 840 ┆ 904 ┆ 438 ┆ 335 ┆ 43     ┆       ┆       ┆       │
│ 79  ┆ 67  ┆ 85  ┆ 81  ┆ 531 ┆ 373 ┆ 774 ┆ 25  ┆ 39  ┆ 478 ┆ 121 ┆        ┆       ┆       ┆       │
│ -1. ┆ -0. ┆ -0. ┆ -0. ┆ 1.4 ┆ 0.0 ┆ -0. ┆ 1.0 ┆ 0.0 ┆ -0. ┆ 2.9 ┆ 0.4925 ┆ 1     ┆ 0     ┆ 0     │
│ 095 ┆ 078 ┆ 484 ┆ 395 ┆ 439 ┆ 487 ┆ 696 ┆ 677 ┆ 057 ┆ 438 ┆ 84  ┆ 26     ┆       ┆       ┆       │
│ 725 ┆ 263 ┆ 084 ┆ 378 ┆ 91  ┆ 63  ┆ 95  ┆ 67  ┆ 98  ┆ 478 ┆     ┆        ┆       ┆       ┆       │
│ 0.8 ┆ -0. ┆ -0. ┆ 0.8 ┆ -0. ┆ 0.9 ┆ 2.3 ┆ 1.2 ┆ 0.1 ┆ 1.7 ┆ -0. ┆ 0.0463 ┆ 1     ┆ 0     ┆ 2     │
│ 966 ┆ 525 ┆ 484 ┆ 498 ┆ 164 ┆ 278 ┆ 877 ┆ 645 ┆ 712 ┆ 118 ┆ 335 ┆ 43     ┆       ┆       ┆       │
│ 56  ┆ 477 ┆ 084 ┆ 89  ┆ 671 ┆ 98  ┆ 15  ┆ 15  ┆ 86  ┆ 04  ┆ 121 ┆        ┆       ┆       ┆       │
│ 1.0 ┆ 2.6 ┆ 2.6 ┆ -0. ┆ 0.3 ┆ 2.6 ┆ 1.5 ┆ 0.9 ┆ -0. ┆ 3.8 ┆ -0. ┆ 0.0463 ┆ 1     ┆ 0     ┆ 2     │
│ 777 ┆ 050 ┆ 812 ┆ 699 ┆ 948 ┆ 861 ┆ 711 ┆ 693 ┆ 656 ┆ 620 ┆ 335 ┆ 43     ┆       ┆       ┆       │
│ 81  ┆ 26  ┆ 44  ┆ 777 ┆ 64  ┆ 7   ┆ 86  ┆ 93  ┆ 157 ┆ 86  ┆ 121 ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┘

## Observation

The numerical variables were standardized while the encoded categorical variables remained unchanged.

In [11]:
scaled_df.write_csv(
    processed_path / "maternal_health_standardized.csv"
)

print("Standardized dataset saved successfully.")

Standardized dataset saved successfully.

## Observation

The standardized dataset has been saved and will be used as the input for Logistic Regression.

In [12]:
print("Processed Dataset Shape")

print(df.shape)

print()

print("Standardized Dataset Shape")

print(scaled_df.shape)

Processed Dataset Shape
(30000, 15)

Standardized Dataset Shape
(30000, 15)

# Summary

The preprocessing stage has successfully prepared the dataset for machine learning.

## Completed tasks:

- Removed unnecessary features.
- Encoded categorical variables.
- Saved the processed dataset.
- Standardized numerical variables.
- Saved the standardized dataset.

These outputs provide two versions of the dataset:

## Dataset	Purpose
maternal_health_processed.csv	Decision Tree & Random Forest
maternal_health_standardized.csv	Logistic Regression

The next stage is Model Development, where the processed datasets will be split into training and testing sets, followed by baseline modelling using Logistic Regression and performance comparison with Decision Tree and Random Forest.